#!/usr/bin/env bash
# ============================================================
# LAMMPS build script — generated by Molecule3D Workbench
# by Shuvam Banerji Seal
# Target: Linux · preset=most · accelerator=kokkos-cuda
# (Captured via Playwright from https://shuvam-banerji-seal.github.io/lammps-web-gui/)
# jobs manually set to 24 via UI; Kokkos_ARCH still VOLTA70 (will be patched to AMPERE80 for A100)
# ============================================================
set -euo pipefail
git clone --depth 1 --branch develop https://github.com/lammps/lammps.git lammps
cd lammps
mkdir -p build && cd build
cmake \
    ../cmake \
    -D PKG_AMOEBA=yes \
    -D PKG_ASPHERE=yes \
    -D PKG_BOCS=yes \
    -D PKG_BODY=yes \
    -D PKG_BPM=yes \
    -D PKG_BROWNIAN=yes \
    -D PKG_CG-DNA=yes \
    -D PKG_CG-SPICA=yes \
    -D PKG_CLASS2=yes \
    -D PKG_COLLOID=yes \
    -D PKG_COLVARS=yes \
    -D PKG_COMPRESS=yes \
    -D PKG_CORESHELL=yes \
    -D PKG_DIELECTRIC=yes \
    -D PKG_DIFFRACTION=yes \
    -D PKG_DIPOLE=yes \
    -D PKG_DPD-BASIC=yes \
    -D PKG_DPD-MESO=yes \
    -D PKG_DPD-REACT=yes \
    -D PKG_DPD-SMOOTH=yes \
    -D PKG_DRUDE=yes \
    -D PKG_EFF=yes \
    -D PKG_ELECTRODE=yes \
    -D PKG_EXTRA-COMMAND=yes \
    -D PKG_EXTRA-COMPUTE=yes \
    -D PKG_EXTRA-DUMP=yes \
    -D PKG_EXTRA-FIX=yes \
    -D PKG_EXTRA-MOLECULE=yes \
    -D PKG_EXTRA-PAIR=yes \
    -D PKG_FEP=yes \
    -D PKG_GRANSURF=yes \
    -D PKG_GRANULAR=yes \
    -D PKG_GRAPHICS=yes \
    -D PKG_INTERLAYER=yes \
    -D PKG_KOKKOS=yes \
    -D PKG_KSPACE=yes \
    -D PKG_LEPTON=yes \
    -D PKG_MACHDYN=yes \
    -D PKG_MANYBODY=yes \
    -D PKG_MC=yes \
    -D PKG_MEAM=yes \
    -D PKG_MESONT=yes \
    -D PKG_MISC=yes \
    -D PKG_ML-IAP=yes \
    -D PKG_ML-POD=yes \
    -D PKG_ML-SNAP=yes \
    -D PKG_ML-UF3=yes \
    -D PKG_MOFFF=yes \
    -D PKG_MOLECULE=yes \
    -D PKG_OPENMP=yes \
    -D PKG_OPT=yes \
    -D PKG_ORIENT=yes \
    -D PKG_PERI=yes \
    -D PKG_PHONON=yes \
    -D PKG_PLUGIN=yes \
    -D PKG_QEQ=yes \
    -D PKG_REACTION=yes \
    -D PKG_REAXFF=yes \
    -D PKG_REPLICA=yes \
    -D PKG_RHEO=yes \
    -D PKG_RIGID=yes \
    -D PKG_SHOCK=yes \
    -D PKG_SPH=yes \
    -D PKG_SPIN=yes \
    -D PKG_SRD=yes \
    -D PKG_TALLY=yes \
    -D PKG_UEF=yes \
    -D PKG_VORONOI=yes \
    -D PKG_YAFF=yes \
    -D Kokkos_ENABLE_CUDA=yes \
    -D CMAKE_CXX_STANDARD=17 \
    -D Kokkos_ARCH_VOLTA70=yes \
    -D CMAKE_BUILD_TYPE=Release
cmake --build . --parallel 24
sudo cmake --install .
lmp -h | head -n 30
